#!/usr/bin/perl

use warnings;
use strict;
use Getopt::Long;
$,="\t";

$SIG{__WARN__} = sub {die @_};

my $usage = "$0 [-h|help]\n
Return one line for each fasta block in input. The first column 
of the line is the header of the block, the remaining part of the
line is the concatenation (without \\n) of the lines of the block.
	-t	separe each original line with a tab in the oneline out
";

my $help=0;
my $tab=0;
GetOptions (
	'h|help' => \$help,
	't|tab'	 => \$tab
) or die($usage);

if($help){
	print $usage;
	exit(0);
}

my $HEADER=undef;
while(<>){
	chomp;
	if(m/^>/){
		print "\n" if defined $HEADER;
		$HEADER = $_;
		$HEADER =~ s/^>//;
		print "$HEADER\t";
	}else{
		die("HEADER not defined") if !defined($HEADER);
		print $_;
		print "\t" if $tab;
	}
}

print "\n" if defined $HEADER;
