cluster: qsub
restart-times: 0
max-jobs-per-second: 10
max-status-checks-per-second: 10
jobs: 3
rerun-incomplete: true  # recomended for cluster submissions
keep-going: true
singularity-args: "-B $REFERENCE_ROOT:$REFERENCE_ROOT"
