cluster: "qsub -V -l select=1:ncpus={threads} " 
restart-times: 0
max-jobs-per-second: 10
max-status-checks-per-second: 10
jobs: 3
rerun-incomplete: true  # recomended for cluster submissions
keep-going: true
latency-wait: 10
#singularity-args: "--bind $REFERENCE_ROOT,$PRJ_ROOT"
