NCPUS: 28

GENCODE_SPECIES: "hsapiens"
GENCODE_VERSION: '32'
GENOME_ASSEMBLY: "GRCh38"

TRIPLEXATOR_MIN_LEN: 8

TRIPLEXATOR_SCORE_CUTOFF: 8

TRIPLEXATOR_DOCKER: "v1.3.2_l6"
# v1.3.2_l6 | v0.02

TRIPLEXATOR_ALN: 1
# 1 | 0

OUTCOMES_COL_NAME: "neg_pos"

PREDICTORS_COL_NAMES:
        - "Stability_norm_undercount"
#        - "Stability_norm_overcount"
        - "Stability_best"
#        - "t_pot_custom"
        - "t_pot_norm"
#        - "PROB__fitted_model"
        - "TTS_covered_frac" 
        - "Score_best"
       
RNAPLFOLD_WINDOW_SIZE: 200

RNAPLFOLD_SPAN_SIZE: 150

RNAPLFOLD_UNPAIRED_WINDOW: 8

SINGLE_STRANDEDNESS_CUTOFF:
        - "0"
#        - "10"
#       - "20"
#       - "50"

RNAPLFOLD_WINDOW:
        - "unpairedWindow"
#        - "singleNt"

ENCODE_DIR: /sto1/ref/bioinfotree/task/encode-screen/dataset/v13

ENCODE_CONDITIONS:
        - ASTROCYTE
        - BcellAdult
        - commonMyeloidProg33
        - fibroblastArmAdult
        - fibroblastLungEmbryo
        - fibroDermis
        - GM12878
        - GM23338
        - H1
        - H9
        - HCT116
        - HeLaS3
        - HepG2
        - HEP_H9
        - IMR90
        - K562
        - Karpas422
        - KERATIN
        - largeIntestEmbryo
        - MCF7
        - MESENC_H1
        - MESEND_H1
        - MONOCYTE
        - MYOTUBE
        - NPC_H9
        - OCILY7
        - ovaryAdult
        - Panc1
        - PANCREAS
        - PC3
        - placenta113
        - psoasMuscle
        - smallIntest108
        - TcellMale21
        - TcellMale37

TPXcCRE_SCORE_SUMMARIZE_METHODS:
        - stability.norm_undercount
        - stability.best
        - tpx_score.best
        - triplexator_t_pot

