NCPUS: 28

GENCODE_SPECIES: "mmusculus"
GENCODE_VERSION: "M25"
GENOME_ASSEMBLY: "GRCm38"

FASTA_SHUFFLE_K:
      - "1"
      - "2"
      - "3"
      - "4"

PEAK_VERSION: "v8.7_ReChIRP_idr_overlap_top1000_mouse" 
