NCPUS: 28

GENCODE_SPECIES: "hsapiens"
GENCODE_VERSION: "37"
GENOME_ASSEMBLY: "GRCh38"
GENOME: "hg38"
PEAK_VERSION: "v8.6_ReChIRP_idr_overlap_top1000"
SEED: 4565
MIN_LEN: 8
ERROR_RATE: 20
G_RATE: 40
CONS_ERROR: 1
SSTRAND: 0
