NCPUS: 28

GENCODE_SPECIES: "mmusculus"
GENCODE_VERSION: "M25"
GENOME_ASSEMBLY: "GRCm38"
GENOME: "mm10"

PEAK_VERSION: "v8.7_ReChIRP_idr_overlap_top1000_mouse"

SEED: 4565

MIN_LEN: 8
ERROR_RATE: 20
G_RATE: 40
CONS_ERROR: 1
SSTRAND: 0
