def all_selected_ssRNA_id():
	with open("selected_ssRNA", mode='rt') as fh:
		for line in fh:
			ssRNA = line.rstrip()
			yield ssRNA

def get_all_triplexator_selected_input(wildcards):
	for ssRNA in all_selected_ssRNA_id():
		for target in expand("tpx_paramspace/{ssRNA}_ss{single_strandedness_cutoff}_{window}/{ssRNA}.neg_pos_rand.bed/{params}/raw.tpx.custom_summary.neg_pos.gz",
				params = triplexator_paramspace.instance_patterns,
				ssRNA = all_selected_ssRNA_id(),
				single_strandedness_cutoff = config["SINGLE_STRANDEDNESS_CUTOFF"],
				window=config["RNAPLFOLD_WINDOW"]
			):
			yield target

ruleorder: lncSmad7 > get_fasta

rule lncSmad7:
	input:
		"../../local/share/data/mmusculus/ssRNA_fasta/lncSmad7.fa"
	output:
		"lncSmad7.fa"
	shell: """
		cp {input} {output}
	"""