---
title: "R Notebook"
output: html_notebook
---

```{r}
# Resources
library(ggplot2)
library(dplyr)
library(glmnet)

# working directory
setwd("/sto1/epigen/TPXcCRE/dataset")

# Dataframe
df <- read.table("tpx_paramspace_AUC.ALL_noSingleNt.method.Npeaks_version.noPROB_fitted.noT_pot_custom.technique.header_added.gz", header=T)

# Set params as factors and relevel 
groups_factors <- c("peak_method_all","ssRNA","singleStrandedness","min_len","error_rate","guanine_rate","repeat_filter","consecutive_error","predictor","technique")
df[,groups_factors] <- lapply(df[,groups_factors] , factor)
df$predictor <- relevel(df$predictor, ref = "t_pot_norm")
df$technique <- relevel(df$technique, ref = "ChIRP-seq")
df$min_len <- relevel(df$min_len, ref = "10")
df$singleStrandedness <- relevel(df$singleStrandedness, ref = "ss50")

# Remove "stability_norm_overcount"
df <- df[!grepl("Stability_norm_overcount", df$predictor),]
df$predictor <- as.factor(as.character(df$predictor))

```


# Filtro il dataframe per avere solo i lncRNA con evidenze di triplex

```{r}
# Computational: Epr, DACOR1
# Experimental: TERC, NEAT1, HOTAIR, Meg3, MEG3, ANRIL, lncSmad7
# Speculated: Tug1

#triplex_evidence_ssRNA <- c("Eprn", "AC087482.1", "TERC", "NEAT1", "HOTAIR", "MEG3", "Meg3", "CDKN2B-AS1", "lncSmad7")
triplex_evidence_ssRNA <- c("TERC", "NEAT1", "HOTAIR", "MEG3", "Meg3", "CDKN2B-AS1", "lncSmad7")

df <- df %>% filter(ssRNA %in% triplex_evidence_ssRNA)
df$ssRNA<-as.factor(as.character(df$ssRNA))
```


# Density plot AUC

```{r}
for (factor in groups_factors) {
  p <- ggplot(df, aes(x = AUC)) + 
    geom_density(aes_string(fill = factor), position = 'identity', alpha = 0.5) +
  print(p)
}
```


# Covert factor to dummy variables

```{r}
factor2dummy<-function(data,col_name){
  mm<-model.matrix(as.formula(paste("~ ", col_name, " - 1")), data)
  col_index <- which(colnames(data)==col_name)
  data %>% select_(-col_index) -> data
  return(cbind(data,mm))
}

for(variable in groups_factors){
  df<-factor2dummy(df,variable)
}
```


# GLMnet

```{r}
y <- df$AUC
x <- df %>% select(-AUC)
x <- as.matrix(x)

cv <- cv.glmnet(x, y, alpha=0)

model <- glmnet(x, y, alpha = 0, lambda = cv$lambda.min)

coef(model)
write.table(file="glmnet_true_coef", as.data.frame(t(as.matrix(c))), row.names = F, quote = F, sep="\t")
```

# GLMnet empirical anova exclude

```{r}
df %>% select(-AUC) -> df_reduced
df_reduced[,grep("predictor", colnames(df_reduced), invert=T)] -> x_reduced
x_reduced <- as.matrix(x_reduced)

cv_reduced <- cv.glmnet(x, y, alpha=0)
model_reduced <- glmnet(x_reduced, y, alpha = 0, lambda = cv$lambda.min)

r2_full_vs_reduced <- model$dev.ratio - model_reduced$dev.ratio


```



# Permutations

```{r}

y=sample(y)
model_full_random <- glmnet(x, y, alpha = 0, lambda = cv$lambda.min)
c_full_random <- coef(model_full_random)
model_reduced_random <- glmnet(x_reduced, y, alpha = 0, lambda = cv_reduced$lambda.min)
r2_full_vs_reduced_random <- model_full_random$dev.ratio - model_reduced_random$dev.ratio

retval_random_coef <- as.data.frame(t(as.matrix(c_full_random)))
retval_r2_full_vs_reduced_random <- c(r2_full_vs_reduced_random)

for(i in seq(1,10000)){
  y=sample(y)
  model_full_random <- glmnet(x, y, alpha = 0, lambda = cv$lambda.min)
  c_full_random <- coef(model_full_random)
  model_reduced_random <- glmnet(x_reduced, y, alpha = 0, lambda = cv_reduced$lambda.min)
  r2_full_vs_reduced_random <- model_full_random$dev.ratio - model_reduced_random$dev.ratio
  
  retval_random_coef <- rbind(retval_random_coef,as.data.frame(t(as.matrix(c_full_random))))
  retval_r2_full_vs_reduced_random <- c(retval_r2_full_vs_reduced_random,r2_full_vs_reduced_random)
}

write.table(file="glmnet_random_coef", retval_random_coef, row.names = F, quote = F, sep="\t")
write.table(file="glmnet_anova_exclude", as.data.frame(r2_full_vs_reduced_random=retval_r2_full_vs_reduced_random), row.names = F, quote = F, sep="\t")

```


# Empirical p-value

```{r}
random_coef <- read.delim("glmnet_random_coef", header = T)
true_coef <- read.delim("glmnet_true_coef", header = T)

for (param in colnames(random_coef)) {
  param_true_coef <- true_coef[,param]
  if(param_true_coef > 0){
    empirical_pval <- sum(random_coef[,param] > param_true_coef)/10000
  } 
  else {
    empirical_pval <- sum(random_coef[,param] < param_true_coef)/10000
  }
  print(param)
  print(empirical_pval)
}
```


# Plot density

```{r}
pdf(file = "permutation_test_density_plot.pdf",paper = "a4")
for (param in colnames(random_coef)) {
  p <- ggplot(random_coef, aes_string(x=param)) + 
    geom_density() + 
    geom_vline(data = true_coef, aes_string(xintercept=param), color = "red") +
    theme_classic()
  print(p)
}
dev.off()
```





