---
title: "R Notebook"
output: html_notebook
---

```{r}
# Resources
library(ggplot2)
library(ggpubr)
library(dplyr)
library(pROC)
library(ggsci)

# working directory
setwd("/sto1/epigen/TPXcCRE/dataset")
```


```{r}
z <- read.table("v8.10_TFBS/ALL_TFs.fimo_score.matrix.header_added.gz", header = T)

z_split<-split(z,z$Gene_ID)

roc_matrix<-lapply(z_split, function(x){
  Gene_ID_name<-levels(as.factor(x$Gene_ID))
  predictor_name<-"score"
  rocobj <- suppressMessages(roc(as.formula(paste(collapse = "~", c("neg_pos", predictor_name))), data= x, direction="<"))
  pROC::smooth(roc = rocobj, method = "binormal")
})

labels <- levels(as.factor(z$Gene_ID))

for(i in seq_along(labels)){
  l<-labels[[i]]
  auc<-round(roc_matrix[[l]]$auc,3)
  labels[[i]]<-paste0(c(l,auc),collapse=" - ")
  }
  
  p<-ggroc(roc_matrix) +
    theme_classic(base_size = 10) +
    geom_segment(aes(x = 1, xend = 0, y = 0, yend = 1), color="darkgray", linetype="dashed",size=0.3) +
    theme(plot.margin = margin(1,2,1,2, "cm")
          , plot.title = element_text(hjust = 0.5)
          , legend.title = element_blank()
          , legend.position = c(0.85, 0.3)
          , legend.key.size = unit(0.4, "cm"))+
    coord_fixed() +
    scale_color_igv(labels = labels)
  
  print(p)

ggsave(filename = "ALL_TFs.ROC_curves.smoothed.pdf", plot = p, device = "pdf")                       
```





```{r}
avg_roc <- read.delim("avg_roc_pre.tsv.avg1", header=T)

avg_roc2 <- avg_roc %>% group_by(ssRNA, spec_bin) %>% summarise(mean_spec = mean(spec_bin_avg), mean_sens = mean(sens)) 

avg_roc2 <- avg_roc2 %>%
  group_by(spec_bin) %>%
  summarise(mean_mean_sens = mean(mean_sens)
            , mean_spec = mean(mean_spec)
            , ymin = mean(mean_sens) - sd(mean_sens)/2
            , ymax = mean(mean_sens) + sd(mean_sens)/2
            , ymin2 = min(mean_sens)
            , ymax2 = max(mean_sens)
            , median_sens = median(mean_sens)
            , ymin3 = quantile(mean_sens, probs = c(0.25))[1]
            , ymax3 = quantile(mean_sens, probs = c(0.75))[1])

# aggiungere 0 e 1
avg_roc2 <- rbind(avg_roc2, c(0,1,0,1,1,1,1,1,1,1))
avg_roc2 <- rbind(avg_roc2, c(1,0,1,0,0,0,0,0,0,0))
	


# plot
p <- ggplot(avg_roc2) +
    scale_x_reverse() +
    geom_ribbon(aes(x = mean_spec, y = mean_mean_sens, ymin = ymin2, ymax = ymax2), fill = "grey70", alpha = 0.4) +
    #geom_ribbon(aes(x = mean_spec, y = mean_mean_sens, ymin = ymin3, ymax = ymax3), fill = "orange", alpha = 0.5) +
    geom_ribbon(aes(x = mean_spec, y = mean_mean_sens, ymin = ymin, ymax = ymax), fill = "grey70", alpha = 0.4) +
    geom_line(aes(x = mean_spec, y = mean_mean_sens)) +
    theme_classic() +
    coord_fixed() +
    geom_segment(aes(x = 1, xend = 0, y = 0, yend = 1), color="darkgray", linetype="dashed", size = 0.3) +
    theme(plot.margin = margin(1,2,1,2, "cm"))

print(p)

ggsave(filename = "average_TFs_ROC.smoothed.pdf", plot = p, device = "pdf")
```





