---
title: "[Publish] ROC comparison"
output:
  pdf_document: default
  html_notebook: default
---

```{r packages, message=TRUE, warning=TRUE, results="hide"}
library(pROC)
library(ggplot2)
library(ggsci)
```

Custom function: _roc.list()_

```{r roc.list}
roc.list <- function(matrix, outcomes, predictors, direction="auto", smoothing=NULL){
  matrix[,predictors] <- sapply(matrix[,predictors],function(x){x <- as.numeric(x)})
  matrix[,predictors][sapply(matrix[,predictors], is.infinite)] <- 1000
  roc.formula <- as.formula(paste(collapse = "~", c(outcomes, paste(collapse = "+", predictors))))
  if(length(predictors)>1){
    roc_list <- suppressMessages(roc(roc.formula, data = matrix, direction = direction, na.rm = T))
  } else if(length(predictors)==1){
    roc_list <- list()
    roc_list[[predictors]] <- suppressMessages(roc(roc.formula, data = matrix, direction = direction, na.rm = T))
  }
  roc_list
}
```

Custom function: _plot.roc()_

The function read a list of rock obj and create a roc plot printing AUC value.

```{r compute.roc}
plot.roc <- function(roc.list, smoothing=NULL){
  if(!is.null(smoothing)){
    roc.list <- lapply(roc.list, function(x){smooth(x, method=smoothing)})
  }
  labels <- names(roc.list)
  for(i in seq_along(labels)){
    l<-labels[[i]]
    auc<-round(roc.list[[l]]$auc,3)
    labels[[i]]<-paste0(c(l,auc),collapse=": ")
  }
  ggroc(roc.list) + 
    geom_segment(aes(x = 1, xend = 0, y = 0, yend = 1), color="darkgrey", linetype="dashed") +
    theme_classic(base_size = 10) +
    theme(plot.margin = margin(1,2,1,2, "cm")
          , plot.title = element_text(hjust = 0.5)
          , legend.title = element_blank()
          , legend.position = c(0.75, 0.22)) +
    scale_color_aaas(labels=labels,) +
    coord_fixed()
}
```

Custom function: _auc.df()_

```{r auc.df}
auc.df <- function(roc.list, smoothing=NULL){
  auc.df <- as.data.frame(do.call(rbind, lapply(roc.list, function(x){x$auc})))
  auc.df$pred <- row.names(auc.df)
  row.names(auc.df) <- NULL
  colnames(auc.df)[which(names(auc.df) == "V1")] <- "AUC"
  auc.df
}
```


# Transcript shuffling framework [K=1]
```{r transcr.shuffle}
transcr.shuffle.hm <- read.delim("v8.summary_transcript_shuffle/matrix.human_mouse.tpx_method.gz", header=T)
transcr.shuffle.hm <- split(transcr.shuffle.hm, transcr.shuffle.hm$tpx_method)

transcr.shuffle.hm.roc <- lapply(transcr.shuffle.hm, function(x){
  roc.list(x,"pos_neg","k1")
})
print(plot.roc(roc.list = lapply(transcr.shuffle.hm.roc,"[[","k1"), smoothing = "binormal"))
```


# Genomic peaks shuffling framework
```{r peaks_shuffle}
peaks.shuffle.hm <- read.delim("v8.summary_peaks_shuffle/matrix.human_mouse.tpx_method.gz", header=T)
peaks.shuffle.hm <- split(peaks.shuffle.hm, peaks.shuffle.hm$tpx_method)

peaks.shuffle.hm.roc <- lapply(peaks.shuffle.hm, function(x){
  roc.list(x,"pos_neg","score")
})
print(plot.roc(roc.list = lapply(peaks.shuffle.hm.roc,"[[","score"), smoothing = "binormal"))
```


# AVG ROC version - Genomic Peaks shuffling 
```{r}
pos_neg_peak_sub_hm <- read.delim("v_test_randomiz_sub.summary.clean.sens_spec.tpx_method.gz",header=T)

pos_neg_peak_sub_hm <- pos_neg_peak_sub_hm %>% mutate(spec_bin = cut(specificities, breaks=c(0, 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1), include.lowest=T))

pos_neg_peak_sub_hm_avg <- pos_neg_peak_sub_hm %>%
  group_by(spec_bin, tpx_method) %>%
  summarise(  mean_sens = mean(sensitivities)
            , mean_spec = mean(specificities)
            , ymin = mean(mean_sens) - sd(sensitivities)/2
            , ymax = mean(mean_sens) + sd(sensitivities)/2
            , ymin2 = min(sensitivities)
            , ymax2 = max(sensitivities)
            , median_sens = median(sensitivities)
            , ymin3 = quantile(sensitivities, probs = c(0.25))[1]
            , ymax3 = quantile(sensitivities, probs = c(0.75))[1])

ggplot(pos_neg_peak_sub_hm_avg) +
  scale_x_reverse() +
  geom_ribbon(aes(x = mean_spec, y = mean_sens, ymin = ymin2, ymax = ymax2, group=tpx_method), fill = "grey90") +
  geom_ribbon(aes(x = mean_spec, y = mean_sens, ymin = ymin, ymax = ymax, group=tpx_method), fill = "grey50") +
  geom_line(aes(x = mean_spec, y = mean_sens, color=tpx_method)) +
  theme_classic() +
  coord_fixed() +
  geom_segment(aes(x = 1, xend = 0, y = 0, yend = 1), color="darkgray", linetype="dashed", size = 0.3) +
  theme(plot.margin = margin(1,2,1,2, "cm"))
```



