selected_lncRNA.ENCODE_NPC_H9: /sto1/epigen/ENCODE_RNAseq/dataset/NPC_H9/DGE/selected_lncRNA
	cut -f 7 $< > $@

GEP.count.exp_filter.ltmm.metadata.max_exp_in_condition.biotype.len.gz: /sto1/epigen/ENCODE_RNAseq/dataset/NPC_H9/GEP.count.exp_filter.ltmm.metadata.max_exp_in_condition.biotype.len.gz
	cp $< $@
