gencode_dir_prefix: /home/reference_data/bioinfotree/task/gencode/dataset

seed: 42

randomization_num: 100

pato:
        sim_sequences: 256
        other_parameters: ""


RNAplfold:
        window_size: 200
        span_size: 150
        unpaired_window: 8


TTS_bed:
        ucsc_dark_gray: 843
        dark_gray_stability: 43


species_gencode_version_map:
        hsapiens: 37
        mmusculus: m32

species_genome_version_map:
        hsapiens: GRCh38
        mmusculus: GRCm39

tss_ref_name: MANE.GRCh38.v1.1.refseq_genomic.Symbol.tss.1500_500


# Null fields must be valorised to run the test
dsDNA_predefined: null

enrichment_test:
        ssRNA: "null"
        genes_of_interest: "null"
        genes_all: "null"

prom_stab_test:
        putative_target_genes: "null"
        background_genes: "null"
        score: "null"
promoter_stability_test:
        tblist: "null"
        score: "null"