# ------------ # 
# 3plex config #
# ------------ #

pato:
        min_length: 10
        max_length: -1
        error_rate: 20
        guanine_rate: 40
        filter_repeat: off
        consecutive_errors: 1
        other_parameters: ""

RNAplfold:
        single_strandedness_cutoff: 0



# ------------------------- #
# Advanced workflows config #
# ------------------------- #

# Mandatory for all workflows ---

# path to ssRNA [FASTA]
ssRNA: path/to/ssRNA.fa
# path to dsDNA [FASTA|BED]
dsDNA: path/to/dsDNA.bed|fa
# path to genome assembly [FASTA]
# wget -O primary_assembly.genome.fa.gz -c "http://ftp.ebi.ac.uk/pub/databases/gencode/Gencode_human/release_32/GRCh38.primary_assembly.genome.fa.gz"; zcat GRCh38.primary_assembly.genome.fa.gz > GRCh38.primary_assembly.genome.fa
genome_fasta: /home/reference_data/bioinfotree/task/gencode/dataset/hsapiens/32/GRCh38.primary_assembly.genome.fa



# Promoter stability test specific ---

# path to universe of genes [one column TXT]
genes_all: path/to/universe_of_genes.txt
# path to genes of interest [one column TXT]
genes_of_interest: path/to/genes_of_interest.txt
# path to promoters [mandatory:  chr | start | end | gene_id ]
promoters_ref_bed: path/to/promoters.bed
# tpx scores to compare promoters
score:
        - Stability_best
        - Stability_norm
# params to run gene set enrichment
gsea:
        max_genes_in_set: 10000
        min_genes_in_set: 5
        nperm: 1000
        gsea_weight: 0



# Random region test specific ---

# path to blacklist file to remove when shuffling genomic regions [BED]
# curl -OJ "https://raw.githubusercontent.com/Boyle-Lab/Blacklist/master/lists/mm10-blacklist.v2.bed.gz"
shuffle_blacklist: path/to/shuffle_blacklist.bed
# path to chrom.info file
# wget -O >(zcat | bawk '{print $1,1,$2}' | bedtools sort | cut -f 1,3 > chrom.info) "http://hgdownload.cse.ucsc.edu/goldenpath/hg38/database/chromInfo.txt.gz"
chrom_info: path/to/chrom.info
# Number of randomization to build the null model [INT]
randomization_num: 1000



# Other ---

dsDNA_predefined: null
