dsDNA_predefined: null
species: hsapiens
triplexator:
        min_length: 9
        max_length: -1
        error_rate: 20
        guanine_rate: 40
        filter_repeat: off
        consecutive_errors: 1
        SSTRAND: 0
tss_ref_name: MANE.GRCh38.v1.1.refseq_genomic.Symbol.tss.1500_500

tblist: "ssRNA_tblist.tsv.gz"
#target_gene_list: MELTF_AS1_targets
#background_gene_list: exp_genes
#ssRNA: MELTF_AS1