# General config

species: hsapiens




# 3plex config

pato:
        min_length: 9
        max_length: -1
        error_rate: 20
        guanine_rate: 40
        filter_repeat: off
        consecutive_errors: 1
        other_parameters: ""

RNAplfold:
        single_strandedness_cutoff: 10




# Advanced workflows config

# Null fields must be valorised to run the test

dsDNA_predefined: null

prom_stab_test:
        putative_target_genes: "null"
        background_genes: "null"
        score: "null"

enrichment_test:
        genes_of_interest: genes_of_interest.txt
        genes_all: genes_all.txt
        gsea:
                max_genes_in_set: 10000
                min_genes_in_set: 5
                gsea_weight: 0

promoter_stability_test:
        tblist: "null"
        score: "null"