dsDNA_predefined: null
species: hsapiens
triplexator:
        min_length: 9
        max_length: -1
        error_rate: 20
        guanine_rate: 40
        filter_repeat: off
        consecutive_errors: 1

tss_ref_name: MANE.GRCh38.v1.1.refseq_genomic.Symbol.tss.1500_500

# Regulatory Regions Test
promoter_stability_test:
        tblist: "ssRNA_tblist.tsv"
        score: "Stability_best"

# enrichment test
enrichment_test:
        ssRNA: "LINC01693"
        genes_of_interest: "genes_of_interest.tsv"
        genes_all: "genes_all.tsv"