gencode_dir_prefix: /home/reference_data/bioinfotree/task/gencode/dataset

species: hsapiens

seed: 42

randomization_num: 100

pato:
        sim_sequences: 256
        other_parameters: ""

RNAplfold:
        window_size: 200
        span_size: 150
        unpaired_window: 8

TTS_bed:
        ucsc_dark_gray: 843
        dark_gray_stability: 43

species_gencode_version_map:
        hsapiens: 37
        mmusculus: m32

species_genome_version_map:
        hsapiens: GRCh38
        mmusculus: GRCm39

tss_ref_name: MANE.GRCh38.v1.1.refseq_genomic.Symbol.tss.1500_500


ssRNA: path/to/ssRNA.fa
dsDNA: path/to/dsDNA.fa


genes_all: path/to/genes_all.txt
genes_of_interest: path/to/genes_of_interest.txt
score: "null"
gsea:
        max_genes_in_set: "null"
        min_genes_in_set: "null"
        nperm: "null"
        gsea_weight: "null"


promoter_stability_test:
        tblist: "null"
        score: "null"