# General config

tss_ref_bed: /home/reference_data/bioinfotree/task/gencode/dataset/hsapiens/37/MANE.GRCh38.v1.1.refseq_genomic.Symbol.tss.1500_500.bed
transcript_fastas: /home/reference_data/bioinfotree/task/gencode/dataset/hsapiens/37/transcripts.longest.fa.gz
genome_fasta: /home/reference_data/bioinfotree/task/gencode/dataset/hsapiens/37/GRCh38.primary_assembly.genome.fa



# 3plex config

pato:
        min_length: 9
        max_length: -1
        error_rate: 20
        guanine_rate: 40
        filter_repeat: off
        consecutive_errors: 1
        other_parameters: ""

RNAplfold:
        single_strandedness_cutoff: 10




# Advanced workflows config


dsDNA_predefined: null

from_sequences:
        # path/to/ssRNA.fa
        ssRNA: path/to/ssRNA.fa
        # path/to/dsDNA.fa
        dsDNA: path/to/dsDNA.fa

promoter_tpx_stability_test:
        # path/to/ssRNA.fa
        ssRNA: ../../../3plex/dataset/ref_enrichment_test/LINC01693.fa 
        # path/to/universe_of_genes
        genes_all: ../../../3plex/dataset/ref_enrichment_test/genes_all.txt 
        # path/to/genes_of_interest
        genes_of_interest: ../../../3plex/dataset/ref_enrichment_test/genes_of_interest.txt 
        score: 
                - Stability_best
                - Stability_norm
        gsea:
                max_genes_in_set: 10000
                min_genes_in_set: 5
                nperm: 1000
                gsea_weight: 0

promoter_stability_test:
        tblist: "null"
        score: "null"