# General config

# path to genome assembly [FASTA]
genome_fasta: path/to/assembly.fa
#/home/reference_data/bioinfotree/task/gencode/dataset/hsapiens/37/GRCh38.primary_assembly.genome.fa

# path to MANE promoters [BED]
tss_ref_bed: path/to/MANE.bed
#/home/reference_data/bioinfotree/task/gencode/dataset/hsapiens/37/MANE.GRCh38.v1.1.refseq_genomic.Symbol.tss.1500_500.bed

# path to transcript [FASTA]
transcript_fastas: path/to/transcript.fa
#/home/reference_data/bioinfotree/task/gencode/dataset/hsapiens/37/transcripts.longest.fa.gz




# 3plex config

pato:
        min_length: 10
        max_length: -1
        error_rate: 20
        guanine_rate: 40
        filter_repeat: off
        consecutive_errors: 1
        other_parameters: ""

RNAplfold:
        single_strandedness_cutoff: 0




# Advanced workflows config

dsDNA_predefined: null

from_sequences:
        # path to ssRNA [FASTA]
        ssRNA: path/to/ssRNA.fa
        # path to dsDNA [FASTA|BED]
        dsDNA: path/to/dsDNA.fa

promoter_tpx_stability_test:
        # path to ssRNA [FASTA]
        ssRNA: path/to/ssRNA.fa
        # path to universe of genes [one column TXT]
        genes_all: path/to/genes_all.txt
        # path to genes of interest [one column TXT]
        genes_of_interest: path/to/genes_of_interest.txt
        score: 
                - Stability_best
                - Stability_norm
        gsea:
                max_genes_in_set: 10000
                min_genes_in_set: 5
                nperm: 1000
                gsea_weight: 0

promoter_stability_test:
        tblist: "null"
        score: "null"