gencode_dir_prefix: /home/reference_data/bioinfotree/task/gencode/dataset

seed: 42

randomization_num: 100

triplexator_other:
        other_parameters: ""

RNAplfold:
        window_size: 200
        span_size: 150
        unpaired_window: 8
        single_strandedness_cutoff: 0

TTS_bed:
        ucsc_dark_gray: 843
        dark_gray_stability: 43

pato_simultaneus_sequences: 256

species_gencode_version_map:
        hsapiens: 37
        mmusculus: m32

species_genome_version_map:
        hsapiens: GRCh38
        mmusculus: GRCm39
