
triplexator_other:
        other_parameters: ""

RNAplfold:
        window_size: 200
        span_size: 150
        unpaired_window: 8
        single_strandedness_cutoff: 0

TTS_bed:
        ucsc_dark_gray: 843
        dark_gray_stability: 43

pato_simultaneus_sequences: 256