# ------------ # 
# 3plex config #
# ------------ #

pato:
        min_length: 10
        max_length: -1
        error_rate: 20
        guanine_rate: 40
        filter_repeat: off
        consecutive_errors: 1
        other_parameters: ""

RNAplfold:
        single_strandedness_cutoff: 0



# ------------------------- #
# Advanced workflows config #
# ------------------------- #

# Mandatory for all workflows ---

# path to ssRNA [FASTA]
ssRNA: path/to/ssRNA.fa
# path to dsDNA [FASTA|BED]
dsDNA: path/to/dsDNA.bed|fa
# path to genome assembly [FASTA]
genome_fasta: path/to/primary_assembly.genome.fa



# Promoter stability test specific ---

# path to universe of genes [one column TXT]
genes_all: path/to/universe_of_genes.txt
# path to genes of interest [one column TXT]
genes_of_interest: path/to/genes_of_interest.txt
# path to promoters [mandatory:  chr | start | end | gene_id ]
tss_ref_bed: path/to/promoters.bed
# tpx scores to compare promoters
score:
        - Stability_best
        - Stability_norm
# params to run gene set enrichment
gsea:
        max_genes_in_set: 10000
        min_genes_in_set: 5
        nperm: 1000
        gsea_weight: 0



# Random region test specific ---

# path to blacklist file to remove when shuffling genomic regions [BED]
shuffle_blacklist: path/to/shuffle_blacklist.bed
# path to chrom.info file
chrom_info: path/to/chrom.info
# Number of randomization to build the null model [INT]
randomization_num: 1000



# Promoter stability test [ssRNA list version] ---

# path to transcript [FASTA]
transcript_fastas: path/to/transcript.fa

promoter_stability_test:
        tblist: "null"
        score: "null"



# Other ---

dsDNA_predefined: null
