---
title: "R Notebook"
output: html_notebook
---

```{r}
setwd("/sto1/epigen/TPXcCRE/dataset/v13_InVitroDiff")

library(ggplot2)
library(dplyr)
z<-read.table("tpx_paramspace.fisher_select_cutoff.matrix.best.up_down", header = T)
z$mark_seqc<-as.factor(z$mark_seqc)

ggplot(data=z %>% filter(min_length==10 & cCRE_type=="dELS" & condition=="NPC_H9"), aes(x=reorder(ssRNA,-TPXcCRE_score), y=TPXcCRE_score, fill=mark_seqc))+geom_col()+facet_grid(condition~cCRE_type,scales="free_x")+theme_bw()+theme(text =element_text(size=11),axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1))+geom_hline(yintercept=log10(0.05),linetype="dashed")+geom_hline(yintercept=-log10(0.05), linetype="dashed")+geom_hline(yintercept=0, linetype="dotted")


#ggplot(data=z_sel, aes(x=reorder(lncRNA,-score), y=score, color=upregulated, size=len))+geom_point()+facet_wrap(~cCRE,scales="free_x",ncol=1)+theme_bw()+theme(text =element_text(size=18),axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1))+geom_hline(yintercept=log10(0.05),linetype="dashed")+geom_hline(yintercept=-log10(0.05), linetype="dashed")+geom_hline(yintercept=0, linetype="dotted")

```



```{r}
library(ggplot2)
library(dplyr)

z<-read.table("tpx_paramspace.fisher_select_cutoff.matrix.best.up_down", header = T)
z$mark_seqc<-as.factor(z$mark_seqc)
z$score_type<-as.factor(z$score_type)
z$to_order<-paste(z$condition,z$ssRNA,sep="_")
recover_labels <- function(x) sub("[^_]*_","",x )

min_length_list <- c(8,10)
cCRE_type_list <- c("PLS","pELS","dELS")
condition_list <- c("HEP_H9","NPC_H9","MESENC_H1","MESEND_H1")
score_type_list <- levels(z$score_type)

plot_list <- list()


for(min_len in min_length_list){
    for(ccre in cCRE_type_list){
      for(s in score_type_list){
        p <- ggplot(data = z %>% filter(min_length == min_len & cCRE_type == ccre & score_type == s), aes(x=reorder(to_order,-TPXcCRE_score), y=TPXcCRE_score, fill=mark_seqc))+
          geom_col()+
          geom_hline(yintercept= log10(0.05),linetype="dashed")+
          geom_hline(yintercept=-log10(0.05), linetype="dashed")+
          geom_hline(yintercept=0, linetype="dotted")+
          facet_grid(cCRE_type~condition,scales="free_x")+
          theme_bw()+
          #theme(text =element_text(size=11),axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1))+
          theme(axis.title.x=element_blank(),axis.text.x=element_blank(),axis.ticks.x=element_blank())+
          scale_x_discrete(labels=recover_labels)+
          labs(title = paste("min_len: ", min_len, ", score_type:",s,sep=" "))
      
        #plot_list[[toString(min_len)]][[ccre]][[cond]] <- p
        plot_list[[toString(min_len)]][[ccre]][[s]] <- p
        
      }
    }
  }

```




```{r, fig.align='center', results = "asis"}

for(min_len in min_length_list){
  for(s in score_type_list){
    for(ccre in cCRE_type_list){
        p <- plot_list[[toString(min_len)]][[ccre]][[s]]
        print(p)
    }
  }
}
      
```


```{r}
for(min_len in min_length_list){
  
  for(ccre in cCRE_type_list){
      
      p <- ggarrange(plotlist = plot_list[[toString(min_len)]][[ccre]], ncol = 1, common.legend = T)
      print(p)
  }
}

```



